-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_Settings" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "SHOW_ONBOARDING_ON_STARTUP" BOOLEAN NOT NULL DEFAULT true,
    "USE_RAINBOW_MODE" BOOLEAN NOT NULL DEFAULT true,
    "PLAYER_PATH" TEXT NOT NULL DEFAULT '',
    "TAGGER_PATH" TEXT NOT NULL DEFAULT '',
    "LIBRARY_PATH" TEXT NOT NULL DEFAULT '',
    "COVERS_PATH" TEXT NOT NULL DEFAULT '',
    "DISCOGS_KEY" TEXT NOT NULL DEFAULT '',
    "DISCOGS_SECRET" TEXT NOT NULL DEFAULT ''
);
INSERT INTO "new_Settings" ("COVERS_PATH", "DISCOGS_KEY", "DISCOGS_SECRET", "LIBRARY_PATH", "PLAYER_PATH", "SHOW_ONBOARDING_ON_STARTUP", "TAGGER_PATH", "id") SELECT "COVERS_PATH", "DISCOGS_KEY", "DISCOGS_SECRET", "LIBRARY_PATH", "PLAYER_PATH", "SHOW_ONBOARDING_ON_STARTUP", "TAGGER_PATH", "id" FROM "Settings";
DROP TABLE "Settings";
ALTER TABLE "new_Settings" RENAME TO "Settings";
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
