-- CreateTable
CREATE TABLE "Settings" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT DEFAULT 1,
    "USE_SMART_IMPORT" BOOLEAN NOT NULL DEFAULT false,
    "PLAYER_PATH" TEXT NOT NULL DEFAULT '',
    "TAGGER_PATH" TEXT NOT NULL DEFAULT '',
    "LIBRARY_PATH" TEXT NOT NULL DEFAULT '',
    "COVERS_PATH" TEXT NOT NULL DEFAULT '',
    "DISCOGS_KEY" TEXT NOT NULL DEFAULT '',
    "DISCOGS_SECRET" TEXT NOT NULL DEFAULT ''
);
